# Generated by Django 5.2.8 on 2025-12-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='requires_payment',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
