# Generated by Django 5.2.8 on 2025-12-09 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_requires_payment_event_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventpayment',
            constraint=models.UniqueConstraint(fields=('mpesa_checkout_request_id',), name='unique_mpesa_checkout_request'),
        ),
    ]
