# Generated by Django 5.2.8 on 2025-12-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
