# Generated by Django 5.2.8 on 2025-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='if false the notice is hidden from public view'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='If set, the notice will be considered expired after this date', null=True),
        ),
    ]
